### ISSUE TITLE
Socket is not connected が発生する 

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zServer#13]
Socket is not connected (#10057 in Send) が発生してタスクマネージャでないと落とせなくなった。
複数回あり。

zLogのバージョン：2.8.5.10 (で統一したつもりだが古いzLogが混じっている可能性あり)
zLogは1.9～5.6G (WARC除く)で接続した。
![zServer_落ちた](https://github.com/jr8ppg/zServer/assets/79432176/5bd44e71-3a8a-4ce6-b1b1-e367aec96dc7)
![zServer_落ちた2](https://github.com/jr8ppg/zServer/assets/79432176/7f7aff17-fcfe-4ba0-9240-f6d5afece918)
![zServer_落ちた3](https://github.com/jr8ppg/zServer/assets/79432176/ca449145-27c0-40d9-bc62-38d1b02e05ec)

**Comment by jr8ppg** [comment]
例外をhandleしていないからだと思うのだが、どうやって再現させるか。

**Comment by jj8dan** [comment]
思い出す＆思いつく状況は

・FDコンテスト後半に発生した
・各クライアントは無線LANで接続され、zServerには公衆LTE回線を通して接続されます(VPN上に置いた)。電波状況が悪い所で回線はせいぜい2 Mbpsがいいとこです。回線もたまに切れます。
・Z-Linkが切れて再接続すると各クライアントが一斉にログをMergeで送ってくるのでzServerに大量のテキストが送られてくる。
・コンテスト後半はLTEルータのSIMカードのパケット量が料金設定値を超過したので、回線が256 kbpsに制限されたかもしれない
・バッファオーバーフローしたのでは？

**Comment by jr8ppg** [comment]
（３）は今後の課題
