### ISSUE TITLE
Start Logにチャットだけでなく生データを保管したい（was "Save, Save As のあり方"）

### ISSUE THREAD

**Issue by jj8dan** [jr8ppg/zServer#17]
Save, Save As は、現状オンメモリのQSOをセーブしているようです。

私の考え方だと、zServerの存在意義としては全てのQSOを時間順に記録していく点にあると思います（それにはDeleteしたQSOや修正したQSOも履歴として残る）。
コンテスト終了間際あるいは終了後に疑わしいQSOを探しに行きたいのです（ルール的には終了後の訂正はアウトです）。勘違いで消したとか誤修正したとかを。

「全履歴をただただセーブする機能が欲しいです」。

zServer起動時にファイル名を聞いてくるような感じになると思います。
ただ大工事になりそうです？。いや、単にテキストファイルを出力するだけでいいか。解析は他のアプリケーションに任せればいいや。

履歴は膨大になりそうです(HDD/SSDは大容量になってきているから杞憂か)。

背景にあるのは以前、Z-Link状態で2TXしたらTX2が勘違いをして自分のQSO以外(TX1のQSO)を全部消していってしまった事件があります。

**Comment by jr8ppg** [comment]
Saveと言うかjournalの記録ってことですね。

**Comment by jr8ppg** [comment]
定期的（毎時０分など）にファイルのバックアップを取るという手ではどうか

**Comment by jj8dan** [comment]
Log.txt に、メッセージだけではなくて生データを記録してくれればあとで追いかけられるので、
冗長 (Verbose)でLog.txtに記録すれば良いです。1行くるごとにセーブすれば良いのではないだろうか。
![2023-08-27](https://github.com/jr8ppg/zServer/assets/79432176/48ad887d-5ce8-4e61-b3b1-24066f9fee7e)

**Comment by jj8dan** [comment]
Save, Save Asの機能ではなくてStart Logの機能になりますね。

**Comment by jj8dan** [comment]
蛇足：Log.txtは、チャットメッセージが発生して初めて作られるので、単にLog StartしただけではLog.txtは作られない。Log.txtはどこにあるんだと探してしまったがまだ作られてなかっただけだった。

**Comment by jr8ppg** [comment]
コマンドログをONにして下さい。
![image](https://github.com/jr8ppg/zServer/assets/56021425/1248e304-a52b-4c17-811b-525872727a66)
